; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
framework = arduino
lib_deps =
  https://github.com/Modellbahn65/NmraDCC.git#sniff
  knolleary/PubSubClient@~2.8
monitor_speed = 115200

[env:esp32dev]
platform = espressif32
board = esp32dev
build_unflags =
  -std=gnu++11
build_flags =
  -std=gnu++17
  -DCORE_DEBUG_LEVEL=5

[env:esp32deveth]
; use ethernet instead of wifi
platform = espressif32
board = esp32dev
build_flags =
  ${env:esp32dev.build_flags}
  -D USE_ETHERNET
build_unflags =
  ${env:esp32dev.build_unflags}
lib_deps =
  ${env:esp32dev.lib_deps}
  arduino-libraries/Ethernet @ ^2.0.2
